### ISSUE TITLE
SQL formatter

### ISSUE THREAD

**Issue by PeterCullenBurbery** [jonathanlermitage/ij-ilove-devtoys#13]
I would like to request adding the SQL formatting functionality of Dev Toys.

**Comment by jonathanlermitage** [comment]
I think the IDE can already do this?

**Comment by PeterCullenBurbery** [comment]
> 

How do you do this in Datagrip? I contacted JetBrains support regarding this.

**Comment by jonathanlermitage** [comment]
SQL formatting works in IntelliJ Ultimate (with the regular shortcut, Ctrl shift L on Windows).  
Unfortunately, I don't use Datagrip, but I think it should offer the same SQL support as in IntelliJ Ultimate. If it doesn't work, this is probably a bug, or a missing feature.
