### ISSUE TITLE
The IntelliJ I love Devtoys Cron Expression Tool incorrectly processes certain cron expressions. Specifically, the tool does not show future executions for the following expressions:

### ISSUE THREAD

**Issue by thebigdatajedi** [jonathanlermitage/ij-ilove-devtoys#16]
0 18 * * 0: Expected to run every Sunday at 6 PM, but shows no future executions.
30 8 * * 1: Expected to run every Monday at 8:30 AM, but shows incorrect future executions.

Steps to Reproduce:

Open the IntelliJ I love Devtoys Cron Expression Tool.
1. Enter the cron expression 0 18 * * 0.
2. Observe the output which shows no future executions, whereas it should show runs at 6 PM every Sunday.

Expected Behavior:

 - The expression 0 18 * * 0 should schedule a job every Sunday at 6 PM.
 - The expression 30 8 * * 1 should schedule a job every Monday at 8:30 AM.
 
Actual Behavior:

- The tool shows no future executions for 0 18 * * 0.
 - Incorrect execution times for 30 8 * * 1.

Environment:

IntelliJ IDEA version:
IntelliJ IDEA 2024.1.1 (Ultimate Edition)
Build #IU-241.15989.150, built on April 29, 2024
Runtime version: 17.0.10+1-b1207.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  org.intellij.plugins.hcl (241.15989.49)
  com.jetbrains.space (241.15989.9)
  com.jetbrains.edu (2024.4-2024.1-742)
  com.obroom.plugin.toolset (2024.3.1)
  com.logmark.cron.tools.id (1.1-2021.4.28-2)
  co.tula.MermaidChart (1.1.6)
  com.intellij.grazie.pro (0.3.308)
  com.intellij.ml.llm (241.15989.195)
  com.intellij.bigdatatools.core (241.15989.150)
  com.intellij.bigdatatools.binary.files (241.14494.158)
  com.intellij.bigdatatools.rfs (241.15989.150)
  com.github.beansoftapp.reatnative.idea (2024.1.0 RC)
  izhangzhihao.rainbow.brackets (2024.2.3-241)
  pro.bashsupport (4.1.3.241)
  com.smartapplications.stormsections (1.5.8)
  com.github.copilot (1.5.4.5571)
  dev.turingcomplete.intellijdevelopertoolsplugins (4.2.0)
  com.chrisrm.idea.MaterialThemeUI (9.2.1)
  org.mallowigi.idea.MaterialThemeUI.LangAdditions (2024.1.1)
  org.mallowigi.idea.MaterialThemeUI.HighContrast (2024.1.1)
  ru.adelf.idea.dotenv (2024.1)
  com.dmarcotte.handlebars (241.14494.150)
  eu.bolt.boltservertools (1.26)
  com.mallowigi (97.0.0)
  zielu.gittoolbox (500.2.7+233)
  mobi.hsz.idea.gitignore (4.5.3)
  org.intellij.scala (2024.1.20)
  com.intellij.bigdatatools.kafka (241.14494.158)
 com.pixelperfect.gitlab-ci (2023.8.4)
 Kotlin: 241.15989.150-IJ

Plugin version:
 lermitage.intellij.ilovedevtoys (1.10.2)

OS:
macOS 14.4.1

Screenshots:
<img width="505" alt="2024-05-22_03-48-47" src="https://github.com/jonathanlermitage/ij-ilove-devtoys/assets/361634/2399ae96-8ce8-4cea-9c5d-7ad925203491">
<img width="505" alt="2024-05-22_03-50-13" src="https://github.com/jonathanlermitage/ij-ilove-devtoys/assets/361634/f2e7c272-d094-464c-976d-6925c000ec36">

**Comment by jonathanlermitage** [comment]
Hi, can you please increase the value of the "Explain for the next days" field? 2 days is too low. It should work better with a higher value.  
But yeah, this GUI is suboptimal (and the English translation terrible. Any help would be appreciated 😅). I think I should use a higher default value. Maybe 30 days.
